ScoreOnCompletion=true
SubOrDub=sub
PercentageToMarkComplete=85
SaveMpvSpeed=true
ManualProviderSearch=false
SkipOp=true
NextEpisodePrompt=false
AddMissingOptions=true
MyAnimeListClientSecret=
Provider=["anineko","anipub"]
SkipRecap=true
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,REMAP_PROVIDER,CONTINUE_LAST,TRACKER,PROVIDER
MyAnimeListClientID=f76d4c827152327b60654285d221222c
MyAnimeListImported=false
SkipFiller=true
SubsLanguage=english
AlternateScreen=true
MyAnimeListImportDismissed=true
DisabledProviders=[senshi]
MpvArgs=[]
StoragePath=$HOME/.local/share/curd
Player=mpv
SkipEd=true
RofiSelection=false
DiscordPresence=true
TrackingRemote=anilist+myanimelist
TrackingLocal=true
ImagePreview=false
TrackingConfigured=true
DiscordClientId=1287457464148820089
AnimeNameLanguage=english
SubStyle=soft
