## name: Ayu Mirage
## upstream: https://github.com/ayu-theme/ayu-colors

background            #1f2430
foreground            #cccac2
selection_background  #409fff
selection_foreground  #1f2430
url_color             #5ccfe6
cursor                #ffcc66
cursor_text_color    #1f2430

active_tab_background   #1f2430
active_tab_foreground   #ffa759
inactive_tab_background #1f2430
inactive_tab_foreground #5c6773
tab_bar_background      #1f2430

# normal
color0  #171b24
color1  #ed8274
color2  #87d96c
color3  #facc6e
color4  #6dcbfa
color5  #dabafa
color6  #90e1c6
color7  #c7c7c7

# bright
color8  #686868
color9  #f28779
color10 #d5ff80
color11 #ffd173
color12 #73d0ff
color13 #dfbfff
color14 #95e6cb
color15 #ffffff
