## name: Bright Sun (Solarized Light variant)
## custom theme — light bg, deep jewel-tone accents (darkened for heavier text), black body

background            #fdf6e3
foreground            #000000
selection_background  #e3d7b0
selection_foreground  #000000
url_color             #124aac
cursor                #000000
cursor_text_color     #fdf6e3

active_tab_background   #eee8d5
active_tab_foreground   #000000
inactive_tab_background #fdf6e3
inactive_tab_foreground #645f53

# normal
color0  #000000
color1  #a81c1c
color2  #196e19
color3  #8b6300
color4  #124aac
color5  #9c1d73
color6  #096b75
color7  #d6cfbb

# bright
color8  #645f53
color9  #bc2b2b
color10 #208120
color11 #a67600
color12 #2056ba
color13 #b22c83
color14 #10818c
color15 #fdf6e3
