# Wallpaper configuration
# nicerocket.png from ThePrimeagen/anime repo
# Clone first: git clone https://github.com/ThePrimeagen/anime.git ~/Pictures/anime

preload = ~/Pictures/anime/driving.jpeg
wallpaper = ,contain:~/Pictures/anime/driving.jpeg
