## name: Kanagawa Wave
## upstream: https://github.com/rebelot/kanagawa.nvim/

background            #1f1f28
foreground            #dcd7ba
selection_background  #dcd7ba
selection_foreground  #1f1f28
url_color             #72A7BC
cursor                #dcd7ba
cursor_text_color    #1f1f28

active_tab_background   #16161d
active_tab_foreground   #C8C093
inactive_tab_background #16161d
inactive_tab_foreground #727169

# normal
color0  #090618
color1  #c34043
color2  #76946a
color3  #c0a36e
color4  #7e9cd8
color5  #957fb8
color6  #6a9589
color7  #c8c093

# bright
color8  #727169
color9  #e82424
color10 #98bb6c
color11 #e6c384
color12 #7fb4ca
color13 #938aa9
color14 #7aa89f
color15 #dcd7ba

color16 #ffa066
color17 #ff5d62
